MODEL_NAME: "convnext_large_d_320"
PRETRAIN: "laion2b_s29b_b131k_ft_soup"
DATASET: 'isaid_zsi_11_4_train'

PIXEL_MEAN: [122.7709383, 116.7460125, 104.09373615]
PIXEL_STD: [68.5005327, 66.6321579, 70.32316305]
INPUT:
  IMAGE_SIZE: 800

W: [0.7, 0.3]

OUTPUT_DIR: "./out"

# PROTOTYPE_NUM: [32, 16, 8, 4, 2, 1]
PROTOTYPE_NUM: [1]

# CHANNEL_NUM: [700, 600, 500, 400, 300, 200, 100]
CHANNEL_NUM: [300]

# VIS_CHANNEL_NUM: [40, 80, 120, 160]
VIS_CHANNEL_NUM: [160]

RESULTS: 'inference/coco_instances_results.json'